version: '3.8'

services:
  db:
    image: postgres:16
    container_name: trendsql-db
    environment:
      POSTGRES_DB: trendsql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d trendsql"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trendsql-network

  api:
    build: .
    container_name: trendsql-api
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=trendsql
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    networks:
      - trendsql-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  trendsql-network:
    driver: bridge
